### ISSUE TITLE
Add Police Officer Name

### ISSUE THREAD

**Issue by chrisak86** [chrisak86/Salamah-App#1]
On position 1 : Add the requester name. On position 2: add the last 4 digits of his ID with format ***6789. On position 3: add the name on the police officer assigned, the message should be Officer Ahmed is on this way (male/male officer and female/female Officer

![WhatsApp Image 2024-09-18 at 17 58 44_7253c0c5](https://github.com/user-attachments/assets/07e73eef-3666-4837-90f8-79b85164322b)

**Comment by tariqarbi03** [comment]
fixed
