### ISSUE TITLE
Portal Issues 7->10

### ISSUE THREAD

**Issue by chrisak86** [chrisak86/Salamah-App#4]
7 - In the Portal: under tickets tab: 
    a - The tickets timestamp column should be added and displayed for every request.
    b-  filter tickets by status and sort ascending descending option should be available
8- In Portal: under police tab, please also display joining date column
9- In the Portal: On dashboard, when we turn off police station they disappear instead of showing as offline.
10- In portal: On Dashboard, map is not showing active tickets. The map in addition to online hospitals/fire/police is should display active tickets

**Comment by tariqarbi03** [comment]
fixed
